server:
  port: 8083

spring:
  application:
    name: risk-service
    main:
      allow-bean-definition-overriding: true  # sécurité


patient:
  service:
    url: http://localhost:8081
note:
  service:
    url: http://localhost:8082

# Feign + logs
logging:
  level:
    com.medilabo.risk: DEBUG
    org.springframework.cloud.openfeign: DEBUG
