version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: medilabo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: patientdb
      MYSQL_USER: medilabo_user
      MYSQL_PASSWORD: mdp
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  mongo:
    image: mongo:7.0
    container_name: medilabo-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 10

  patient-service:
    build:
      context: .
      dockerfile: patient-service/Dockerfile
    image: medilabo/patient-service
    container_name: medilabo-patient-service
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/patientdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: medilabo_user
      SPRING_DATASOURCE_PASSWORD: mdp
    ports:
      - "8081:8081"

  note-service:
    build:
      context: .
      dockerfile: note-service/Dockerfile
    image: medilabo/note-service
    container_name: medilabo-note-service
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/notesdb
    ports:
      - "8082:8082"

  risk-service:
    build:
      context: .
      dockerfile: risk-service/Dockerfile
    image: medilabo/risk-service
    container_name: medilabo-risk-service
    depends_on:
      patient-service:
        condition: service_started
      note-service:
        condition: service_started
    ports:
      - "8083:8083"

  gateway-service:
    build:
      context: .
      dockerfile: gateway-service/Dockerfile
    image: medilabo/gateway-service
    container_name: medilabo-gateway-service
    depends_on:
      patient-service:
        condition: service_started
      note-service:
        condition: service_started
      risk-service:
        condition: service_started
    ports:
      - "8080:8080"

  front-service:
    build:
      context: .
      dockerfile: front-service/Dockerfile
    image: medilabo/front-service
    container_name: medilabo-front-service
    depends_on:
      gateway-service:
        condition: service_started
    environment:
      # correspond Ã  gateway.base-url dans application.yml
      GATEWAY_BASE_URL: http://gateway-service:8080
    ports:
      - "8084:8084"

volumes:
  mysql_data:
  mongo_data:
