server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/patientdb?useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: medilabo_user
    password: mdp

  jpa:
    hibernate:
      ddl-auto: update          # cr√©e/ajuste la table patients si besoin
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: always




